// Generated by `make skills` from audit.server (run_job); edit that, not this.
// A skill, not an MCP tool, so that it can refuse a delegated task (_lib/delegated.js).

const { forwardSkill } = require("../_lib/runner");

const SPEC = {"service": "audit", "env": "AUDIT_SOCKET", "op": "run_job", "params": {"name": "string"}};

module.exports.runtime = {
  handler: async function (params) {
    return forwardSkill(this, SPEC, params);
  },
};
