// Generated by `uv run hostctl skills` from podcasts.server (remove_podcast); edit that, not this.
// A skill, not an MCP tool, so that it can refuse a delegated task (_lib/delegated.js).

const { forwardSkill } = require("../_lib/runner");

const SPEC = {"service": "podcasts", "env": "PODCASTS_SOCKET", "op": "remove_podcast", "params": {"slug": "string"}};

module.exports.runtime = {
  handler: async function (params) {
    return forwardSkill(this, SPEC, params);
  },
};
