// Generated by `uv run hostctl skills` from sites.server (delete_entry); edit that, not this.
// A skill, not an MCP tool, so that it can refuse a delegated task (_lib/delegated.js).

const { forwardSkill } = require("../_lib/runner");

const SPEC = {"service": "sites", "env": "SITES_SOCKET", "op": "delete_entry", "params": {"site": "string", "section": "string", "slug": "string"}};

module.exports.runtime = {
  handler: async function (params) {
    return forwardSkill(this, SPEC, params);
  },
};
