"""Write the agent skills that only forward an op to a host service, from their declarations.

A front declares such an op with `hostrpc.Skills` (`@skills.add` on a signature with a
docstring and no body, like its MCP tools). This module turns each into
anythingllm/agent-skills/<op, with - for _>/: a plugin.json with the docstring and the
parameters' descriptions and types, from the same JSON schema the MCP server would give
the op, and a handler.js that hands the call to `forwardSkill` (_lib/runner.js). Both are
committed, as AnythingLLM reads the repo's files as they are; `make skills` writes them and
`tools/skills.py --check` (run by make diff and deploy) says when they're stale.

Run in the dev venv (`uv run --all-packages`): it imports every front, and mcp.
"""

from __future__ import annotations

import asyncio
import importlib
import json
from pathlib import Path
from typing import Any

from hostrpc import Skills

GENERATED = "// Generated by `make skills` from"
SKILLS_DIR = Path("anythingllm") / "agent-skills"


def fronts(root: Path) -> list[str]:
    """The modules (<package>.server) that declare skills."""
    return sorted(
        f"{p.parent.name}.server"
        for p in root.glob("packages/*/src/*/server.py")
        if "hostrpc.Skills(" in p.read_text()
    )


def declared(root: Path) -> list[tuple[str, Skills]]:
    """(module, its Skills) for every front that declares skills."""
    out = []
    for name in fronts(root):
        skills = getattr(importlib.import_module(name), "skills", None)
        if not isinstance(skills, Skills):
            raise TypeError(f"{name} mentions hostrpc.Skills but has no `skills`")
        out.append((name, skills))
    return out


def _schema(fn) -> tuple[str, dict[str, Any]]:
    """The op's description and input schema, as its MCP tool would have them."""
    from mcp.server.mcpserver import MCPServer

    server = MCPServer("skillgen")
    server.add_tool(fn)
    (tool,) = asyncio.run(server.list_tools())
    return tool.description or "", tool.input_schema


def _param(name: str, prop: dict[str, Any]) -> tuple[dict[str, Any], str]:
    """A JSON-schema property as a plugin.json param, and its kind for forwardSkill."""
    branches = [b for b in prop.get("anyOf", [prop]) if b.get("type") != "null"]
    types = [b.get("type") for b in branches]
    if types == ["integer", "string"]:
        kind, branch = "integer-or-string", {"type": "string"}
    elif len(branches) == 1 and types[0] in ("string", "boolean", "object", "integer"):
        kind, branch = types[0], branches[0]
    else:
        raise ValueError(f"{name}: no skill param type for {prop}")
    param: dict[str, Any] = {"type": branch["type"]}
    if "enum" in branch:
        param["enum"] = branch["enum"]
        kind = "enum"
    if prop.get("description"):
        param["description"] = prop["description"]
    return param, kind


def _plugin(op: str, description: str, params: dict[str, Any]) -> str:
    folder = op.replace("_", "-")
    manifest = {
        "active": True,
        "hubId": folder,
        "name": op.replace("_", " ").title(),
        "schema": "skill-1.0.0",
        "version": "1.0.0",
        "description": " ".join(description.split()),
        "author": "anything",
        "license": "MIT",
        "imported": True,
        "examples": [],
        "entrypoint": {"file": "handler.js", "params": params},
    }
    return json.dumps(manifest, indent=2) + "\n"


def _handler(module: str, skills: Skills, op: str, kinds: dict[str, str]) -> str:
    spec = {"service": skills.folder, "env": skills.env, "op": op, "params": kinds}
    return (
        f"{GENERATED} {module} ({op}); edit that, not this.\n"
        "// A skill, not an MCP tool, so that it can refuse a delegated task (_lib/delegated.js).\n"
        "\n"
        'const { forwardSkill } = require("../_lib/runner");\n'
        "\n"
        f"const SPEC = {json.dumps(spec)};\n"
        "\n"
        "module.exports.runtime = {\n"
        "  handler: async function (params) {\n"
        "    return forwardSkill(this, SPEC, params);\n"
        "  },\n"
        "};\n"
    )


def render(root: Path) -> dict[Path, str]:
    """Every generated file, by path under `root`."""
    out: dict[Path, str] = {}
    for module, skills in declared(root):
        for fn in skills:
            op = fn.__name__
            description, schema = _schema(fn)
            params, kinds = {}, {}
            for name, prop in schema.get("properties", {}).items():
                params[name], kinds[name] = _param(f"{op}.{name}", prop)
            folder = root / SKILLS_DIR / op.replace("_", "-")
            if folder / "plugin.json" in out:
                raise ValueError(f"two fronts declare the skill {op}")
            out[folder / "plugin.json"] = _plugin(op, description, params)
            out[folder / "handler.js"] = _handler(module, skills, op, kinds)
    return out


def generated(root: Path) -> set[Path]:
    """The skill folders in the repo that were generated (their handler.js says so)."""
    return {
        h.parent
        for h in (root / SKILLS_DIR).glob("*/handler.js")
        if h.read_text().startswith(GENERATED)
    }


def stale(root: Path) -> list[str]:
    """What `write` would change, as repo-relative paths; empty when up to date."""
    files = render(root)
    out = [
        str(p.relative_to(root))
        for p, text in files.items()
        if not p.exists() or p.read_text() != text
    ]
    folders = {p.parent for p in files}
    out += [str(d.relative_to(root)) + "/" for d in sorted(generated(root) - folders)]
    return out


def write(root: Path) -> list[str]:
    """Write every generated file and remove generated skills no longer declared. A skill
    folder written by hand is never overwritten. Returns what changed."""
    files = render(root)
    for folder in {p.parent for p in files}:
        handler = folder / "handler.js"
        if handler.exists() and not handler.read_text().startswith(GENERATED):
            raise ValueError(
                f"{folder.relative_to(root)} is a hand-written skill; remove it first"
            )
    changed = stale(root)
    for d in generated(root) - {p.parent for p in files}:
        for f in sorted(d.rglob("*"), reverse=True):
            f.unlink() if f.is_file() else f.rmdir()
        d.rmdir()
    for p, text in files.items():
        if not p.exists() or p.read_text() != text:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(text)
    return changed
