"""Write the agent skills that only forward an op to a host service, from their declarations.

A front declares such an op with `hostrpc.Skills` (`@skills.add` on a signature with a
docstring and no body, like its MCP tools). This module turns each into
anythingllm/agent-skills/<op, with - for _>/: a plugin.json with the docstring and the
parameters' descriptions and types, from the same JSON schema the MCP server would give
the op, and a handler.js that hands the call to `forwardSkill` (_lib/runner.js). Both are
committed, as AnythingLLM reads the repo's files as they are; `uv run hostctl skills` writes them and
`hostctl.skills --check` (run by uv run hostctl diff and deploy) says when they're stale.

Run in the dev venv (`uv run --all-packages`): it imports every front, and mcp.
"""

from __future__ import annotations

import asyncio
import importlib
import json
import shutil
from pathlib import Path
from typing import Any

from hostrpc import Skills

GENERATED = "// Generated by `uv run hostctl skills` from"
SKILLS_DIR = Path("anythingllm") / "agent-skills"


def declared(root: Path) -> list[tuple[str, Skills]]:
    """(module, its Skills) for every front (<package>.server) that declares skills."""
    out = []
    for path in sorted(root.glob("packages/*/src/*/server.py")):
        name = f"{path.parent.name}.server"
        skills = getattr(importlib.import_module(name), "skills", None)
        if isinstance(skills, Skills):
            out.append((name, skills))
    return out


def _schemas(skills: Skills) -> list[tuple[str, str, dict[str, Any]]]:
    """(op, description, input schema) of each skill, as its MCP tool would have them."""
    from mcp.server.mcpserver import MCPServer

    server = MCPServer("skillgen")
    for fn in skills:
        server.add_tool(fn)
    tools = asyncio.run(server.list_tools())
    return [(t.name, t.description or "", t.input_schema) for t in tools]


def _param(name: str, prop: dict[str, Any]) -> tuple[dict[str, Any], str]:
    """A JSON-schema property as a plugin.json param, and its kind for forwardSkill."""
    branches = [b for b in prop.get("anyOf", [prop]) if b.get("type") != "null"]
    types = [b.get("type") for b in branches]
    if types == ["integer", "string"]:  # a number or a word, e.g. keep: 5 or "all"
        kind, branch = "integer", {"type": "string"}
    elif len(branches) == 1 and types[0] in ("string", "boolean", "object", "integer"):
        kind, branch = types[0], branches[0]
    else:
        raise ValueError(f"{name}: no skill param type for {prop}")
    param: dict[str, Any] = {"type": branch["type"]}
    if "enum" in branch:
        param["enum"] = branch["enum"]
        kind = "enum"
    if prop.get("description"):
        param["description"] = prop["description"]
    return param, kind


def _plugin(op: str, description: str, params: dict[str, Any]) -> str:
    folder = op.replace("_", "-")
    manifest = {
        "active": True,
        "hubId": folder,
        "name": op.replace("_", " ").title(),
        "schema": "skill-1.0.0",
        "version": "1.0.0",
        "description": " ".join(description.split()),
        "author": "anything",
        "license": "MIT",
        "imported": True,
        "examples": [],
        "entrypoint": {"file": "handler.js", "params": params},
    }
    return json.dumps(manifest, indent=2) + "\n"


def _handler(module: str, skills: Skills, op: str, kinds: dict[str, str]) -> str:
    spec = {"service": skills.folder, "env": skills.env, "op": op, "params": kinds}
    return (
        f"{GENERATED} {module} ({op}); edit that, not this.\n"
        "// A skill, not an MCP tool, so that it can refuse a delegated task (_lib/delegated.js).\n"
        "\n"
        'const { forwardSkill } = require("../_lib/runner");\n'
        "\n"
        f"const SPEC = {json.dumps(spec)};\n"
        "\n"
        "module.exports.runtime = {\n"
        "  handler: async function (params) {\n"
        "    return forwardSkill(this, SPEC, params);\n"
        "  },\n"
        "};\n"
    )


def render(root: Path) -> dict[Path, str]:
    """Every generated file, by path under `root`."""
    out: dict[Path, str] = {}
    for module, skills in declared(root):
        for op, description, schema in _schemas(skills):
            params, kinds = {}, {}
            for name, prop in schema.get("properties", {}).items():
                params[name], kinds[name] = _param(f"{op}.{name}", prop)
            folder = root / SKILLS_DIR / op.replace("_", "-")
            if folder / "plugin.json" in out:
                raise ValueError(f"two fronts declare the skill {op}")
            out[folder / "plugin.json"] = _plugin(op, description, params)
            out[folder / "handler.js"] = _handler(module, skills, op, kinds)
    return out


def _changes(root: Path, files: dict[Path, str]) -> tuple[list[Path], list[Path]]:
    """The files that differ from `files`, and the generated skill folders not in it."""
    changed = [
        p for p, text in files.items() if not p.exists() or p.read_text() != text
    ]
    generated = {
        h.parent
        for h in (root / SKILLS_DIR).glob("*/handler.js")
        if h.read_text().startswith(GENERATED)
    }
    return changed, sorted(generated - {p.parent for p in files})


def stale(root: Path) -> list[str]:
    """What `write` would change, as repo-relative paths; empty when up to date."""
    return _listed(root, *_changes(root, render(root)))


def write(root: Path) -> list[str]:
    """Write every generated file and remove generated skills no longer declared. A skill
    folder written by hand is never overwritten. Returns what changed."""
    files = render(root)
    changed, gone = _changes(root, files)
    for p in changed:
        handler = p.parent / "handler.js"
        if handler.exists() and not handler.read_text().startswith(GENERATED):
            raise ValueError(
                f"{p.parent.relative_to(root)} is a hand-written skill; remove it first"
            )
    for d in gone:
        shutil.rmtree(d)
    for p in changed:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(files[p])
    return _listed(root, changed, gone)


def _listed(root: Path, changed: list[Path], gone: list[Path]) -> list[str]:
    return [str(p.relative_to(root)) for p in changed] + [
        f"{d.relative_to(root)}/" for d in gone
    ]
