// What a skill that fronts one op of a host service needs (most are generated by
// hostrpc.skillgen from a front's `skills`, and call forwardSkill): refuse a delegated task, send
// the op its args over the service's socket, and return the text it answers with. Never
// throws (a skill that throws ends the chat): a failure becomes the reply.

const { call, socketPath, Down, Refused } = require("./hostrpc");
const { delegatedRefusal } = require("./delegated");
const { scopeOf } = require("./scope");

/**
 * `service` is the runner's folder in storage and its unit's name (sites -> sites-runner),
 * `env` the variable that can point at another socket, `reply` what turns the op's result
 * into the text to return (by default the result itself, or its JSON).
 */
async function forward(self, { service, env, op, args, timeoutMs = 120_000, reply = asText }) {
  const refused = delegatedRefusal(self);
  if (refused) return refused;
  const signal = self.super?.abortController?.signal ?? null;
  try {
    const result = await call(socketPath(service, env), op, args, { name: `the ${service} runner`, signal, timeoutMs });
    if (result === null) return "The chat closed.";
    return reply(result);
  } catch (e) {
    self.logger?.(`${op}: ${e?.message || e}`);
    if (e instanceof Down)
      return `The ${service} service isn't running on the server (${e.message}). Tell the user it needs \`uv run hostctl ${service}-setup\`.`;
    if (e instanceof Refused) return `Error: ${e.message}`;
    return `${op} failed: ${e?.message || e}`;
  }
}

/** forward, with the call's scope ({workspace, thread}, from the invocation, never the
 *  model) added to `args`: for an op that acts on the chat's workspace. */
async function forwardScoped(self, { args, ...spec }) {
  return forward(self, { ...spec, args: { scope: scopeOf(self), ...args } });
}

/**
 * A generated skill (hostrpc.skillgen): forward `spec.op` with the params it declares,
 * `spec.params` giving each one's kind. A param left out (or null) is left out, so the
 * op's own default applies; an enum sent as "" counts as left out.
 */
async function forwardSkill(self, { service, env, op, params: kinds }, params) {
  const args = {};
  for (const [name, kind] of Object.entries(kinds)) {
    let value = params?.[name];
    if (value == null || (kind === "enum" && value === "")) continue;
    if (kind === "boolean") value = asFlag(value);
    else if (kind === "object") value = asObject(value);
    else if (kind === "integer") value = asInteger(value);
    if (value != null) args[name] = value;
  }
  return forward(self, { service, env, op, args });
}

/** A number a model sometimes sends as text: digits become a number, anything else (e.g. "all") stays. */
function asInteger(value) {
  return typeof value === "string" && /^\d+$/.test(value.trim()) ? Number(value) : value;
}

function asText(result) {
  return typeof result === "string" ? result : JSON.stringify(result);
}

/** An object argument, which a model sometimes sends as JSON text; null when there's none. */
function asObject(value) {
  if (value == null || value === "") return null;
  if (typeof value === "string") {
    try {
      return JSON.parse(value);
    } catch {
      return value; // the runner says what's wrong with it
    }
  }
  return value;
}

/** A true/false argument, which a model sometimes sends as text; null when it's left out. */
function asFlag(value) {
  if (value == null || value === "") return null;
  return value === true || String(value).toLowerCase() === "true";
}

module.exports = { forward, forwardScoped, forwardSkill, asObject, asFlag, asInteger };
