// Generated by `make skills` from podcasts.server (add_podcast); edit that, not this.
// A skill, not an MCP tool, so that it can refuse a delegated task (_lib/delegated.js).

const { forwardSkill } = require("../_lib/runner");

const SPEC = {"service": "podcasts", "env": "PODCASTS_SOCKET", "op": "add_podcast", "params": {"url": "string", "keep": "integer-or-string", "slug": "string", "scrub_ads": "boolean", "transcribe": "boolean", "ad_words": "enum", "rules": "string"}};

module.exports.runtime = {
  handler: async function (params) {
    return forwardSkill(this, SPEC, params);
  },
};
